# Generated by Django 3.1.7 on 2021-03-04 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210301_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='textPrice',
            new_name='taxPrice',
        ),
    ]
